const PDFContent = {
    title: "VigyanShaala",
    SWOT: {
        strengthLabel: "Strength",
        weaknessLabel: "Weakness",
        opportunityLabel: "Opportunity",
        threatLabel: "Threat",
        strengthDes:"What internal strengths (for example: strong skills, subject areas, best qualities etc.) do you have in relation to this short-term career goal?",
        weaknessDes: "What are your weaknesses (for examples poor habits, traits, skills, training etc.) that can be improved to achieve this short-term goal?",
        opportunityDes: "What external opportunities that you can take advantage of to achieve your short-term goal? You can think about scholarships, fellowships, mentors, educational or training resources that can be useful for your goal.",
        threatDes: "What are the external threats that can prevent you from getting to your goal? Think about issues like a particular skill that became important for your goal which you cannot possibly develop right now, types of competitions in relation to this goal, family issues that might stop you from accomplishing your goal.",
    },
    IDP: {
        goalLabel:"Goal A",
        goalDescription: "What are your long-term professional goal and career aspiration? Please remember, getting a master’s or PhD is not a career aspiration, these are degrees or steps towards your long-term career goal. Think about what you want to become after you get these degrees.",
        nameLabel: "Name",
        nameDescription: "Write your full name",
        education1Label:"Xth/ XIIth",
        education1Description: "What are your percentages in 10th and 12th standard board exams?",
        education2Label: "1st/2nd/3rd /4th year",
        education2Description: "What are your CGPAs or percentages during your undergraduate education? Write scores for the years you have completed.",
        proudMomentsLabel: "My Proud Moments",
        proudMomentDescription: "List professional achievements that made you proud.",
        raisecLabel: "Top 3 Personality Traits (RAISEC) %",
        raisecDescription: "Write top three personality traits and their percentile from RIASEC analysis that you performed.",
        matchStrengthLabel: "Match Strength-Oppn. Strategy",
        matchStrengthDescription: "From your SWOT analysis, write how will you match your strengths and opportunities to achieve your goal.",
        decThreatLabel: "Decrease Threat Strategy",
        decThreatDescription: "Look at the Threat section of your SWOT analysis and come up with strategies that can help reduce your threats.",
        aquiredHardSkillsLabel:"Acquired relevant skills: Hard Skills",
        aquiredHardSkillsDescription: "List hard skills (or technical skills) that you have already gained and will be useful for your long-term career growth.",
        aquiredSoftSkillsLabel: "Acquired relevant skills:Soft Skills",
        aquiredSoftSkillsDescription: "List soft skills (or interpersonal skills) that you have already gained and will be useful for your long-term career growth.",
        goalLabelB: "Goal B",
        goalReWriteDes: "Re-write your long-term professional goal and career aspiration.",
        careerOptionsLabel: "Career Options for this Goal",
        careerOptionDes: "Write what job roles or types are available for this career goal (for example, Research Scientist, Patent Scientist, Market-Researcher etc.). Make sure you include the name of the sector (for example R&D Scientist in Chemistry).",
        hardSkillstoAquireLabel: "Skills to acquire: Hard Skills",
        hardSkillsToAquireDes: "List hard skills (or technical skills) required to attain this career goal. Think about hands-on experimental skills, software packages, coding skills etc.",
        softSkillsToAquireLabel: "Skills to acquire: Soft Skills",
        softSkillsToAquireDes: "List soft skills (or interpersonal skills) required to attain this career goal.",
        employerLabel: "Key Employers/or Universities",
        employerDes: "Think about where are these Career Options Available. List top five Company/Industry or University names",
        mentorsLabel: "My Mentors/or Alumni",
        mentorsDes: "Write down names of mentors, professors, teachers, or seniors from your current organization who can help you achieve your goal.",
        DM1Label: "Developmental Milestones: M1",
        DM1Des: "Breakdown your long-term goal in 3 broad milestones. Imagine your future in 3 broad steps. Write first milestone here.",
        DM2Label: "Developmental Milestones: M2",
        DM2Des: "Breakdown your long-term goal in 3 broad milestones. Imagine your future in 3 broad steps. Write your second milestone here.",
        DM3Label: "Developmental Milestones: M3",
        DM3Des: "Breakdown your long-term goal in 3 broad milestones. Imagine your future in 3 broad steps. Write your third milestone here.",
        M1S1Label: "M1: Step 1",
        M1S1Des: "Breakdown Milestone 1 in three steps and write your step 1 here. Step 1 of Milestone 1 will prepare you for Step 2 of Milestone 1.",
        M1S2Label: "M1: Step 2",
        M1S2Des: "Breakdown Milestone 1 in three steps and write your step 2 here. Step 2 of Milestone 1 will prepare you for Step 3 of Milestone 1.",
        M1S3Label: "M1: Step 3",
        M1S3Des: "Breakdown Milestone 1 in three steps and write your step 3 here. Step 3 of Milestone 1 will prepare you for Step 1 of Milestone 2.",
        M2S1Label: "M2: Step 1",
        M2S1Des: "Breakdown Milestone 2 in three steps and write your step 1 here. Step 1 of Milestone 2 will prepare you for Step 2 of Milestone 2.",
        M2S2Label: "M2: Step 2",
        M2S2Des: "Breakdown Milestone 2 in three steps and write your step 2 here. Step 2 of Milestone 2 will prepare you for Step 3 of Milestone 2.",
        M2S3Label: "M2: Step 3",
        M2S3Des: "Breakdown Milestone 2 in three steps and write your step 3 here. Step 3 of Milestone 2 will prepare you for Step 1 of Milestone 3.",
        M3S1Label: "M3: Step 1",
        M3S1Des: "Breakdown Milestone 2 in three steps and write your step 1 here. Step 1 of Milestone 3 will prepare you for Step 2 of Milestone 3.",
        M3S2Label: "M3: Step 2",
        M3S2Des: "Breakdown Milestone 2 in three steps and write your step 2 here. Step 2 of Milestone 3 will prepare you for Step 3 of Milestone 3.",
        M3S3Label: "M3: Step 3",
        M3S3Des: "Breakdown Milestone 2 in three steps and write your step 3 here. Step 3 of Milestone 3 will help you achieve the final stage of Milestone 3.",
        adjustmentLabel: "Adjustment Needed (When unexpected situations arise)",
        adjustmentDes: "Note down changes you might need to make if some situations change. For example, the entrance exam preparation might turn out to be much tougher – so will have to change the steps accordingly or may be job interview did not go well – so prepare for a break year and add a milestone and steps accordingly",
        reviewLabel: "Review Milestones attained",
        reviewDes: "Write down every significant step or milestone that you have completed here."
    },
    CT: {
        imageHeader: "You receive the following image on WhatsApp in a forwarded message.",
        questionHeader: "Use your critical thinking and scientific temperament skills to answer the following questions in not more than 200 words:",
        questionA: "a)	Before forwarding the message to your friends and relatives, what should you do?",
        questionB: "b)	How would you find out if the news is trustworthy?",
        questionC: "c)	Based on your search for truth, do you think that the claims in this image are absolutely true? Explain the reason behind your thoughts. "
    },
    RIASECContent: {
        question1: "1.	Take the RIASEC Test through these websites and report your findings.",
        question2: "2.	Report the following: ",
        question2a: "A.	Your scores for each of the 6 basic interest areas: ",
        question2b: `B.	A person’s top three interest areas are called their "Holland Code". According to the results obtained from the RIASEC test, what is your Holland Code?`,
        realistic: "Realistic",
        investigative: "Investigative",
        artistic: "Artistic",
        social: "Social",
        enterprising: "Enterprising",
        conventional: "Conventional",
        examlLink: "https://openpsychometrics.org/tests/RIASEC/"
    },
    CollabContent: {
        question1: "1.	Do you prefer working as part of a team or independently? Why?",
        question2: "2.	Tell us about a project when you worked closely with peers to achieve a certain goal. What was your specific role?",
        question3: "3.	Write about a time when you disagreed with your friend while working on a project. How did you resolve the situation and what was the outcome?"
    },
    CAGMContent: {
        question1: "1.	Explain your value of continuous learning with examples.",
        question2: "2.	Who inspires you? Explain the connection between their values and yours, and how this applies to your professional life",
        question3: "3.	Tell us about a time when you received constructive criticism about your work (class assignment, extra-curricular activities, or any other type of work)."
    },
    SMARTGOALSContent: {
            goal: "Short-term goal",
            Specific: "Specific",
            Measurable: "Measurable",
            Achievable: "Achievable",
            Relevant: "Relevant",
            TimeBound: "TimeBound",
            Specific_description: "What specific goal do you have? (Be clear about exactly what the goal is and what will be done to achieve it)",
            Measurable_description: "Make sure you have a way to assess whether you have achieved your goal. How will you track your progress towards achieving your goal? How will you measure your progress towards achieving the goal?",
            Achievable_description: "State how you believe reaching the goal is within your power. Write how much time you can spend daily. Think whether this amount of time is good enough to achieve the goal? ",
            Relevant_description: "State how the goal will help you to meet your overall goals as a student. Write how this goal is relevant to your long-term goal.",
            TimeBound_description:  "The goal should be time bound and not open ended. Give deadlines. Give concrete time in days, weeks, and months. "
    },
    templateSelection: {
        SWOT: "A self-assessment and strategic planning tool to guide you in achieving your short-term goals",
        SMART: "A framework to help you succeed in setting and attaining goals within a certain time period.",
        RIASEC: "A tool to understand your personality and choose careers to increase career satisfaction and success.",
        IDP: "A tool to identify your professional goals, determine skills and experiences required to achieve this goal, and create a plan of action to reach your dream career.",
        COLLABORATION: "Collaboration	Understand the practice of working together to achieve a common goal",
        CAGM: "Practice out-of-the box thinking and develop growth mindset",
        CT: "Understand how to question, analyze, interpret, evaluate and make a judgement"
    }
}

export default PDFContent;